# Welcome to Jekyll!
#

# Site settings
title: finlaymagui.re
description: Bioinformatician and Data Scientist
owner:
  name: Finlay Maguire # or company name
  email: root@finlaymagui.re
  url: http://finlaymagui.re
first_published: 1996 # if migrating another site, the year of your first publish
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://finlaymagui.re" # the base hostname & protocol for your site

# on landing page
greeting: |
  Welcome!  
  I hope you enjoy my little personal page
closing-head: Thanks for visiting
closing-para: Feel free to get in touch. Cheers!

# on all pages
social:
  github: https://github.com/fmaguire
  K: https://www.kaggle.com/finlaymaguire
  twitter: https://twitter.com/FinlayM
  university: https://scholar.google.co.uk/citations?user=rHFCtWwAAAAJ
  linkedin-square: https://uk.linkedin.com/in/finlaymaguire
  book: https://github.com/fmaguire/CV/raw/master/Finlay_Maguire_CV.pdf
  email: mailto:root@finlaymagui.re

# Build settings
permalink: /:categories/:title.html
markdown: kramdown
#sass:
#  style: compressed
include: ['_pages']
defaults:
  - scope:
      path: _pages
    values:
      layout: page
      #permalink: /:slug/ # see github.com/jekyll/jekyll/issues/2280 for restriction
  - scope:
      path: _posts
    values:
      layout: post
